<?php

/**
 * @file
 * Used to add and/or improve game content type.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_games_help($route_name, RouteMatchInterface $route_match) {
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The my_games module is used to add and/or improve game content type.') . '</p>';

      return $output;

}

/**
 * Implements hook_preprocess_comment().
 */
function my_games_preprocess_comment(&$vars) {
  // Change the Permalink to display #1 instead of 'Permalink'
  $comment = $vars['comment'];
  dump($comment);
}
?>
